root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o ./tmp/main.exe cmd/bot/main.go"
bin = "./tmp/main.exe"
delay = 1000 # 1000ms
exclude_dir = ["assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html", "json"]
exclude_regex = ["_test\\.go"]