run:
  timeout: 5m
  concurrency: 8

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      text: "Error return value is not checked"